### ISSUE TITLE
Invalid link in description

### ISSUE THREAD

**Issue by nkhitrov** [alexewerlof/slc#2]
Repo has invalid url in description (`DNS_PROBE_FINISHED_NXDOMAIN` error). It should be updated to https://slc.alexewerlof.com/

<img width="581" alt="image" src="https://github.com/alexewerlof/slc/assets/28262306/a9e14348-57ca-482b-9504-caf7baf88e07">

P.S. I like this project! It's helpful and very interesting. Thank you!

**Comment by Lp-Francois** [comment]
I actually got a certificate issue on the slc. link: https://slc.alexewerlof.com/

<img width="1047" alt="Screenshot 2024-01-24 at 16 14 25" src="https://github.com/alexewerlof/slc/assets/32224751/3e1e5101-e7f4-44c0-bcb4-1a3f045c5f3b">

**Comment by alexewerlof** [comment]
Sorry I somehow missed this issue. The correct url is https://slc.alexewerlof.com/ as @Lp-Francois mentioned.
The certificate issue was due to migration to a new DNS provider.

Everything should work as expected now. I've updated the URL on the repo home page as well.
